//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Travals.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Place
    {
        public int ID { get; set; }
        public string NamePlace { get; set; }
        public byte[] Image { get; set; }
        public string Type { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Location { get; set; }
        public Nullable<int> Visibile { get; set; }
        public Nullable<int> UserID { get; set; }
    }
}
